name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the action on
    paths-ignore:
      - 'kubernetes/app.yaml' 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Extract short commit hash
        id: commit
        run: echo "commit_id=$(git rev-parse --short HEAD)" >> $GITHUB_ENV  # Updated to set an environment variable

      - name: Build Docker image
        run: docker build -t 00mab/crud:${{ env.commit_id }} .

      - name: Push Docker image
        run: docker push 00mab/crud:${{ env.commit_id }}

      - name: Update Kubernetes manifest
        run: |
          sed -i "s|00mab/crud:latest|00mab/crud:${{ env.commit_id }}|g" kubernetes/app.yaml

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9 # Use a dedicated action for git
        with:
          author_name: "MuhmmadAyan"
          author_email: "muhmmadayanashiq@gmail.com"
          message: "Updated manifest"
          add: "kubernetes/app.yaml"
          token: ${{ secrets.GH_TOKEN }}  # Ensure this secret is set in your GitHub repository
